### ISSUE TITLE
Check whether useradd was successful

### ISSUE THREAD

**Issue by pkotvan** [customer10123/Homework#5]
https://github.com/customer10123/Homework/blob/732b158e92f69793453b00c57cf3a1a246d0e757/main.sh#L48

Check whether useradd was successful.

**Comment by pkotvan** [comment]
Don't fail in case user already exists.

**Comment by customer10123** [comment]
Is it necessary to distinguish between whether the user already exists or it was added? (I think it is, but want to make sure)

**Comment by pkotvan** [comment]
Good question!

No you do not need to distinguish between these two events. Both are considered a PASS.

**Comment by customer10123** [comment]
Alright, that simplifies it. Fixed in ba2ce8c9f8df33b9f9b8be0a1a27e44589c6351d
